include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - build
  - test
  - quality
  - security
  - package

cache:
  paths:
    - .m2/repository

# ---------------- BUILD ----------------
build_job:
  stage: build
  image: eclipse-temurin:17-jdk-alpine
  script:
    - ./mvnw clean compile -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

# ---------------- TEST ----------------
test_job:
  stage: test
  image: eclipse-temurin:17-jdk-alpine
  script:
    - ./mvnw test -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

# ---------------- QUALITY ----------------
code_quality_job:
  stage: quality
  image: docker:stable
  services:
    - docker:dind
  script:
    - mkdir codequality-results
    - docker run --rm -e CODECLIMATE_CODE="$PWD" -v "$PWD":/code -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/cc:/tmp/cc codeclimate/codeclimate analyze -f html > codequality-results/index.html
  artifacts:
    paths:
      - codequality-results/
  allow_failure: true

package_job:
  stage: package
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
  script:
    - docker info
    - docker-compose version || true

sast:
  allow_failure: true